#开启REST风格
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true


  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/userinfo
    driver-class-name: com.mysql.jdbc.Driver


    druid:
      aop-patterns: com.example.springboot.*
      filters: stat,wall,slf4j
      stat-view-servlet:
        enabled: true
#        login-username: root
#        login-password: root
        reset-enable: false

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
        slf4j:
          enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          prefer-ip: true
  application:
    name: spring-boot-application

mybatis:
  mapper-locations: classpath:com\example\springboot\test\dao\*.xml
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.example.springboot: debug
    org.springframework: warn


management:
  endpoints:
    enabled-by-default: true #暴露所有端点信息
    web:
      exposure:
        include: '*'  #以web方式暴露





  endpoint:
     health:
       show-details: always




